import type { Metadata } from "next";

import { robotoCondensed } from "@/lib/fonts";

import "@/styles/globals.css";

import { Footer } from "@/components/sections/footer";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoCondensed.className} min-h-screen bg-background antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <main className="flex-1">{children}</main>
            <Footer />
            <TailwindIndicator />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
